### ISSUE TITLE
Add support for secrets

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/kghub-downloader#1]
For example, OMIM requires a key for downloads.  We should also take extra care not to log any urls containing keys (or strip them prior to logging).

**Comment by glass-ships** [comment]
Not necessary for implementation, but we need to track down the `$MONARCHIVE` and `MONARCHIVE_KEY` variables at some point in order to make use of this 
```
# Mind the @ to not leak the key
data/omim/mimTitles.txt: FORCE data/omim/
	@cd $(@D) && $(WGET) $(MONARCHIVE)$(MONARCHIVE_KEY)/mimTitles.txt

# Mind the @ to not leak the key
data/omim/morbidmap.txt: FORCE data/omim/
	@cd $(@D) && $(WGET) $(MONARCHIVE)$(MONARCHIVE_KEY)/morbidmap.txt
```
