### ISSUE TITLE
Add tests and a github workflow to run them 

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/kghub-downloader#4]
We need some basic testing at least, probably move the examples to be integration tests, if not more.

**Comment by kevinschaper** [comment]
There are some tests living in kg-covid-19 that can be brought over:

https://github.com/Knowledge-Graph-Hub/kg-covid-19/blob/master/tests/test_download_from_yaml.py

The tests are commented out due to a bad interaction with GitHub actions, so that will take some work.

An important part is the mocking aspect:

https://github.com/Knowledge-Graph-Hub/kg-covid-19/blob/master/tests/resources/mock_download.py

**Comment by glass-ships** [comment]
This was implemented in #14
