### ISSUE TITLE
Add API support to downloader

### ISSUE THREAD

**Issue by putmantime** [monarch-initiative/kghub-downloader#5]
The downloader needs to be able to support API extract for various sources.

- [ ] implement biomart support for Ensemble ingest (ensembleid to ncbi gene id mapping)
- [ ] Kegg ingest requires API extraction including the use of key for auth

**Comment by glass-ships** [comment]
Circling back to this, we're working on releasing 0.3.0 which introduces passing api keys as secrets, using a backend parsing that looks for "{SECRETS}" in your URL. 

Does this satisfy the Kegg ingest requirement? 

I'm a little confused about the biomart support though

**Comment by putmantime** [comment]
We now support some API authentication.
Closing as we no longer ingest from Ensemble or Kegg directly.
