### ISSUE TITLE
Add option to mirror downloads to bucket

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/kghub-downloader#8]
Maybe as a command line argument it should take the name of a google bucket w/ path to mirror a download to

**Comment by caufieldjh** [comment]
Consider mirrors to different services with https://pypi.org/project/cloudstorage/

**Comment by putmantime** [comment]
@kevinschaper could you elaborate on this issue?
What are the use cases?  Existing projects...Translator, KG-Hub etc?
Are there concerns that need to be addressed for different platforms? e.g. Amazon, google etc

**Comment by putmantime** [comment]
Acceptance criteria for this issue is simply being able to push the source files to a bucket after download.

Make a new download-cache bucket. Directory structure should mirror what's in data directory: nested by source.
